lib/products_web/router.ex
defmodule ProductsWeb.Router do
  use ProductsWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ProductsWeb do
    pipe_through :browser

    get "/products", ProductController, :index
  end
end

lib/products/application.ex
defmodule Products.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      Products.Repo,
      ProductsWeb.Endpoint,
      Products.Scheduler
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Products.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ProductsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/products/repo.ex
defmodule Products.Repo do
  use Ecto.Repo,
    otp_app: :products,
    adapter: Ecto.Adapters.Postgres

  use Scrivener, page_size: 20
end

lib/products/retreiver.ex
defmodule Products.Retreiver do
  require Logger

  alias Products.Shops
  @default_file "MOCK_DATA.csv"

  defp file_path do
    :code.priv_dir(:products)
    |> Path.join(Application.get_env(:products, :data_file, @default_file))
  end

  def get_data do
    file_path()
    |> File.stream!()
    |> CSV.decode()
    |> Stream.drop(1)
    |> Flow.from_enumerable(max_demand: 50)
    |> Flow.filter(fn
      {:ok, _data} ->
        true

      {:error, reason} ->
        Logger.error(reason)
        false
    end)
    |> Flow.map(fn {:ok, data_row} -> data_row end)
    |> Flow.map(&Shops.product_from_list/1)
    |> Flow.run()
  end
end

lib/products/shop/product.ex
defmodule Products.Shop.Product do
  use Ecto.Schema
  import Ecto.Changeset

  @cast_fields [:id, :name, :photo_url, :barcode, :price, :producer]

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}
  schema "products" do
    field :barcode, :string
    field :name, :string
    field :photo_url, :string
    field :price, :integer
    field :producer, :string

    timestamps()
  end

  @doc false
  def changeset(product, attrs) do
    product
    |> cast(attrs, @cast_fields)
    |> validate_required([:id, :name, :price])
  end

  defimpl Jason.Encoder do
    @value_fields [:id, :name, :photo_url, :barcode, :price, :producer]
    def encode(product, opts) do
      Jason.Encode.map(Map.take(product, @value_fields), opts)
    end
  end
end

lib/products/shop/shops.ex
defmodule Products.Shops do
  @moduledoc """
  The Shops context.
  """

  import Ecto.Query, warn: false
  alias Products.Repo

  alias Products.Shop.Product

  def list_products(clauses, options \\ []) do
    Product
    |> where(^clauses)
    |> Repo.paginate(options)
  end

  def product_from_list([name, photo_url, barcode, price, uid, producer]) do
    case Repo.get(Product, uid) do
      nil -> %Product{id: uid}
      product -> product
    end
    |> Product.changeset(%{
      name: name,
      photo_url: photo_url,
      barcode: barcode,
      price: price,
      producer: producer
    })
    |> Repo.insert_or_update()
  end
  def product_from_list(invalid_list) do
    {:error, {:invalid, invalid_list}}
  end
end

lib/products_web/controllers/product_controller.ex
defmodule ProductsWeb.ProductController do
  use ProductsWeb, :controller

  alias Products.Shops

  def index(conn, params) do
    render(conn, :index,
      page:
        Shops.list_products(
          case Map.get(params, "producer", nil) do
            nil -> []
            producer -> [producer: producer]
          end,
          page: Map.get(params, "page", 1),
          page_size: Map.get(params, "page_size", 25)
        )
    )
  end
end

lib/products_web/views/error_view.ex
defmodule ProductsWeb.ErrorView do
  use ProductsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/products_web/views/layout_view.ex
defmodule ProductsWeb.LayoutView do
  use ProductsWeb, :view
end

lib/products_web/views/product_view.ex
defmodule ProductsWeb.ProductView do
  use ProductsWeb, :view

  def render("index.json", %{page: page}) do Map.take(page, [:entries, :page_number, :page_size, :total_pages])
  end
end

lib/products_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Products · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/products_web/templates/product/index.html.eex
<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Barcode</th>
      <th>Price</th>
      <th>Producer</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for product <- @page.entries do %>
        <tr>
          <td><%= product.name %></td>
          <td><img src="<%= product.photo_url %>" /></td>
          <td><%= product.barcode %></td>
          <td><%= product.price %></td>
          <td><%= product.producer %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<nav class="pagination">
  <%= if @page.page_number == 1 do %>
    <a class="button" disabled><<</a>
  <% else %>
    <%= link("<<", to: Routes.product_url(@conn, :index, page: @page.page_number-1, page_size: @page.page_size), class: "button")%>
  <% end %>

  <%= if @page.page_number == @page.total_pages do %>
    <a class="button" disabled>>></a>
  <% else %>
    <%= link(">>", to: Routes.product_url(@conn, :index, page: @page.page_number+1, page_size: @page.page_size), class: "button")%>
  <% end %>
</nav>